### ISSUE TITLE
s.replace is not a function

### ISSUE THREAD

**Issue by rossng** [cellular/oazapfts#45]
I'm trying to use oazapfts to generate a client for the Vimeo API, which has a JSON OpenAPI 3.0.2 spec.

I get the following error:

```
$ npx oazapfts src\generated\vimeo-openapi.json src\lib\vimeoClient.ts   
node_modules\oazapfts\node_modules\typescript\lib\typescript.js:16266
        return s.replace(escapedCharsRegExp, getReplacement);
                 ^

TypeError: s.replace is not a function
    at escapeString (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:16266:18)
    at escapeNonAsciiString (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:16271:13)
    at Object.getLiteralText (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:13486:34)
    at getLiteralTextOfNode (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:98322:23)
    at emitLiteral (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:95932:24)
    at pipelineEmitWithHint (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:95744:32)
    at pipelineEmitWithComments (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:98730:17)
    at pipelineEmit (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:95382:13)
    at emitExpression (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:95367:20)
    at emitLiteralType (node_modules\oazapfts\node_modules\typescript\lib\typescript.js:96310:13)
npm ERR! code 1
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c oazapfts src\generated\vimeo-openapi.json src\lib\vimeoClient.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Temp\nodejs\npm-cache\_logs\2021-01-01T02_32_34_176Z-debug.log
```

[Here's the JSON spec](https://gist.github.com/rossng/9cf6d798234407f150c2080a2c08eab8), to save you the (considerable) trouble of downloading it yourself.

**Comment by rossng** [comment]
FWIW, I just tried wrapping the return statement in a try-catch block and returning `s` when an exception was thrown. It seems to have generated a valid client.

(also - happy new year!)

**Comment by rossng** [comment]
Possible dupe of #40

**Comment by goququ** [comment]
> I just tried wrapping the return statement in a try-catch block and returning `s` when an exception was thrown. It seems to have generated a semi-valid client. However a few of the type names are broken - e.g. `type LegacyError` somehow turned into `type Legacy Error`, which causes lots of problems!
> 
> (also - happy new year!)

Hi, I've got same error. In my case it was bug with enum types generating, where keys were numbers, but this library expect string. It's easy to fix in source code for instant type generation
