### ISSUE TITLE
Crash on `oneOf` with `default` specified

### ISSUE THREAD

**Issue by shocklateboy92** [cellular/oazapfts#51]
Here's my swagger file with the repro case:
```json
{
  "x-generator": "NSwag v13.10.1.0 (NJsonSchema v10.3.3.0 (Newtonsoft.Json v12.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "My Title",
    "version": "1.0.0"
  },
  "paths": {
    "/api/Words/Search": {
      "get": {
        "tags": [
          "Words"
        ],
        "operationId": "Words_Search",
        "parameters": [
          {
            "name": "query",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            },
            "x-position": 1
          },
          {
            "name": "analyzer",
            "in": "query",
            "schema": {
              "default": "SudachiC",
              "oneOf": [
                {
                  "$ref": "#/components/schemas/Analyzer"
                }
              ]
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Analyzer": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "Kuromoji",
          "SudachiA",
          "SudachiB",
          "SudachiC"
        ],
        "enum": [
          "Kuromoji",
          "SudachiA",
          "SudachiB",
          "SudachiC"
        ]
      }
    }
  }
}
```

Running the generator with this input crashes with the following output:
```
fernie@tiberius /tmp/scratch.fernie/erab/frontend (git)-[features/rtk-query] % npx @rtk-incubator/rtk-query-codegen-openapi --hooks ../backend/Erabikata.Backend/obj/swagger.json  > backend.generated.ts
TypeError: Cannot read property 'getBaseTypeFromSchema' of undefined
    at getTypeFromSchema (/tmp/scratch.fernie/erab/frontend/node_modules/oazapfts/lib/codegen/generate.js:303:27)
    at Array.map (<anonymous>)
    at ApiGenerator.getUnionType (/tmp/scratch.fernie/erab/frontend/node_modules/oazapfts/lib/codegen/generate.js:294:70)
    at ApiGenerator.getBaseTypeFromSchema (/tmp/scratch.fernie/erab/frontend/node_modules/oazapfts/lib/codegen/generate.js:320:25)
    at ApiGenerator.getTypeFromSchema (/tmp/scratch.fernie/erab/frontend/node_modules/oazapfts/lib/codegen/generate.js:303:27)
    at generateEndpoint (/tmp/scratch.fernie/erab/frontend/node_modules/@rtk-incubator/rtk-query-codegen-openapi/lib/generate.js:153:30)
    at /tmp/scratch.fernie/erab/frontend/node_modules/@rtk-incubator/rtk-query-codegen-openapi/lib/generate.js:110:122
    at Array.map (<anonymous>)
    at Object.generateApi (/tmp/scratch.fernie/erab/frontend/node_modules/@rtk-incubator/rtk-query-codegen-openapi/lib/generate.js:110:93)
```

However, it no longer crashes when I remove the default value for that argument, like so:
```json
          {
            "name": "analyzer",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/Analyzer"
            },
            "x-position": 2
          }

```

Let me know if you need anything else to narrow down the bug. This project looks very cool so far :smile:

**Comment by Nvveen** [comment]
I believe the offending line is https://github.com/cellular/oazapfts/blob/310117038b6a5119c8a121063d9f4d6f36f43b59/src/codegen/generate.ts#L326

where doing `.map(this.someFunc)` is bad practice because of silent parameters. Better would be to use `.map(schema => this.someFunc(schema))`, although most other occurrences of similar lines in the file do `.map(this.someFunc.bind(this))`, which, although error prone, does work.
